"""Quantifies the Kermany patient-grouping flaw, and its effect on the score.

Why this script exists
----------------------
model/dataset.py groups Kermany images by f"{class_name}-{number}" rather
than by the bare patient number (see its KNOWN LIMITATION docstring). Because
896 of 4,657 numeric ids appear under more than one class folder, one patient
can be split into up to three groups and scattered across train/val/test.

A claim like "our test set is patient-disjoint" should not be defended with
an argument -- it should be defended with a measurement. This script produces
that measurement, so the numbers quoted in README.md / FEATURES.md can be
regenerated by anyone with the dataset rather than taken on trust.

It splits the reserved test set into:
  - LEAKED: images whose numeric patient id also appears in train or val
  - CLEAN : images whose numeric patient id appears in neither
and scores the deployed checkpoint on each, plus the full set for reference.

What it found (2026-08-27, deployed checkpoint):

    full test set   n=13146   acc=0.9517   macroF1=0.9233
    leaked subset   n= 5375   acc=0.9180   macroF1=0.8878
    clean subset    n= 7771   acc=0.9750   macroF1=0.9541

The model scores LOWER on the leaked patients -- the opposite of what
memorization would produce. The leaked group is by construction the
multi-diagnosis patients, which are the clinically ambiguous cases on the
CNV/DRUSEN boundary where the model is weakest. So the headline 95.17% is
conservative rather than inflated, and 97.50% is the genuinely
patient-disjoint figure.

Nothing is written to the database or to the checkpoint directory; this is a
read-only audit.

Usage:
    python -m model.audit_patient_leakage
"""

import json
import os
import re
import sys

import torch
from sklearn.metrics import accuracy_score, f1_score
from torch.utils.data import DataLoader
from torchvision import transforms

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from model.dataset import OCTDataset, collect_samples, filter_by_patients  # noqa: E402
from model.inference import IMAGENET_MEAN, IMAGENET_STD, load_model  # noqa: E402

DATA_ROOT = r"G:\Download\archive\OCT2017"
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKPOINT_PATH = os.path.join(ROOT_DIR, "model", "checkpoints", "resnet50_oct.pth")
SPLIT_PATH = os.path.join(ROOT_DIR, "model", "checkpoints", "patient_split.json")

BATCH_SIZE = 64

# Split-file keys are "CLASS-number"; we want the bare number.
GROUP_KEY_RE = re.compile(r"^[A-Za-z]+-(\d+)$")


def numeric_id(group_key):
    match = GROUP_KEY_RE.match(group_key)
    return match.group(1) if match else group_key


def score(model, samples, class_names, device, transform, label):
    if not samples:
        print(f"{label:<38} (no samples)")
        return
    loader = DataLoader(
        OCTDataset(samples, class_names, transform),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True,
    )
    preds, labels = [], []
    with torch.no_grad():
        for images, targets in loader:
            preds.extend(model(images.to(device)).argmax(1).cpu().tolist())
            labels.extend(targets.tolist())
    acc = accuracy_score(labels, preds)
    macro_f1 = f1_score(labels, preds, average="macro", zero_division=0)
    per_class = f1_score(
        labels, preds, average=None, zero_division=0, labels=list(range(len(class_names)))
    )
    print(f"{label:<38} n={len(samples):>6}  acc={acc:.4f}  macroF1={macro_f1:.4f}")
    print("    per-class F1: " + "  ".join(f"{c}={v:.3f}" for c, v in zip(class_names, per_class)))


def main():
    if not os.path.isfile(SPLIT_PATH):
        print(f"No patient split at '{SPLIT_PATH}' -- run train_full.py first.")
        return
    if not os.path.isdir(DATA_ROOT):
        print(f"Dataset not found at '{DATA_ROOT}'. Check DATA_ROOT in this script.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, checkpoint_loaded, class_names, _ = load_model(CHECKPOINT_PATH, device)
    if not checkpoint_loaded:
        print(f"No checkpoint at '{CHECKPOINT_PATH}'.")
        return

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])

    all_samples = collect_samples(
        os.path.join(DATA_ROOT, "train"),
        os.path.join(DATA_ROOT, "val"),
        os.path.join(DATA_ROOT, "test"),
    )
    with open(SPLIT_PATH, "r", encoding="utf-8") as f:
        split = json.load(f)

    seen_numeric = {numeric_id(k) for k in split["train"]} | {numeric_id(k) for k in split["val"]}
    test_samples = filter_by_patients(all_samples, set(split["test"]))
    leaked = [s for s in test_samples if numeric_id(s[2]) in seen_numeric]
    clean = [s for s in test_samples if numeric_id(s[2]) not in seen_numeric]

    test_numeric = {numeric_id(k) for k in split["test"]}
    print(f"device={device}  classes={class_names}")
    print()
    print("--- grouping audit ---")
    print(f"  test group keys (class-prefixed) : {len(split['test'])}")
    print(f"  distinct numeric patient ids     : {len(test_numeric)}")
    print(f"  also present in train/val        : {len(test_numeric & seen_numeric)}")
    print(f"  test images affected             : {len(leaked)}/{len(test_samples)} "
          f"({100 * len(leaked) / max(len(test_samples), 1):.1f}%)")
    print()
    print("--- scores ---")
    score(model, test_samples, class_names, device, transform, "FULL test set (as reported)")
    score(model, leaked, class_names, device, transform, "LEAKED (patient seen in train/val)")
    score(model, clean, class_names, device, transform, "CLEAN (patient never seen)")
    print()
    print("Expect CLEAN > FULL > LEAKED. That ordering is the finding: the")
    print("leaked group is harder, not easier, so the headline number is")
    print("conservative rather than inflated.")


if __name__ == "__main__":
    main()
